--------------------------------------------------------
--  File created - Thursday-October-25-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BIO_OBSERVATION
--------------------------------------------------------

  CREATE TABLE "BIOMART"."BIO_OBSERVATION" 
   (	"BIO_OBSERVATION_ID" NUMBER(18,0), 
	"OBS_NAME" NVARCHAR2(200), 
	"OBS_CODE" NVARCHAR2(50), 
	"OBS_DESCR" NVARCHAR2(1000), 
	"OBS_TYPE" NVARCHAR2(20), 
	"OBS_CODE_SOURCE" NVARCHAR2(20), 
	"ETL_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BIOMART" ;
--------------------------------------------------------
--  DDL for Index OBSERVATIONDIM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BIOMART"."OBSERVATIONDIM_PK" ON "BIOMART"."BIO_OBSERVATION" ("BIO_OBSERVATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BIOMART" ;
--------------------------------------------------------
--  Constraints for Table BIO_OBSERVATION
--------------------------------------------------------

  ALTER TABLE "BIOMART"."BIO_OBSERVATION" ADD CONSTRAINT "OBSERVATIONDIM_PK" PRIMARY KEY ("BIO_OBSERVATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BIOMART"  ENABLE;
 
  ALTER TABLE "BIOMART"."BIO_OBSERVATION" MODIFY ("OBS_NAME" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Trigger TRG_BIO_OBSERVATION_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BIOMART"."TRG_BIO_OBSERVATION_ID" 
before insert on BIO_OBSERVATION
for each row
begin
  if inserting then
     if :NEW.BIO_OBSERVATION_ID is null then
        select SEQ_BIO_DATA_ID.nextval into :NEW.BIO_OBSERVATION_ID from dual;
     end if;
  end if;
end;

/
ALTER TRIGGER "BIOMART"."TRG_BIO_OBSERVATION_ID" ENABLE;
