--------------------------------------------------------
--  DDL for Table BIO_ANALYSIS_ATTRIBUTE
--------------------------------------------------------

  CREATE TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE" 
   (  "STUDY_ID" VARCHAR2(255 BYTE), 
  "BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0), 
  "TERM_ID" NUMBER(22,0), 
  "SOURCE_CD" VARCHAR2(255 BYTE), 
  "BIO_ANALYSIS_ATTRIBUTE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIOMART" ;
--------------------------------------------------------
--  DDL for Index PK_BAA_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BIOMART"."PK_BAA_ID" ON "BIOMART"."BIO_ANALYSIS_ATTRIBUTE" ("BIO_ANALYSIS_ATTRIBUTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIOMART" ;
--------------------------------------------------------
--  Constraints for Table BIO_ANALYSIS_ATTRIBUTE
--------------------------------------------------------

  ALTER TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE" ADD CONSTRAINT "PK_BAA_ID" PRIMARY KEY ("BIO_ANALYSIS_ATTRIBUTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIOMART"  ENABLE;
 
  ALTER TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE" MODIFY ("BIO_ASSAY_ANALYSIS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE" MODIFY ("BIO_ANALYSIS_ATTRIBUTE_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Trigger TRG_BIO_ANALYSIS_ATTRIBUTE_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BIOMART"."TRG_BIO_ANALYSIS_ATTRIBUTE_ID" 
  before insert on "BIOMART"."BIO_ANALYSIS_ATTRIBUTE"
  for each row
declare
  -- local variables here
begin
  if inserting then       
    if :NEW.BIO_ANALYSIS_ATTRIBUTE_ID is null then
      select SEQ_BIO_DATA_ID.nextval into :NEW.BIO_ANALYSIS_ATTRIBUTE_ID from dual;
    end if;
    
  end if;   
  
end TRG_BIO_ANALYSIS_ATTRIBUTE_ID;

/
ALTER TRIGGER "BIOMART"."TRG_BIO_ANALYSIS_ATTRIBUTE_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BIO_ANALYSIS_ATT_BAAL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BIOMART"."TRG_BIO_ANALYSIS_ATT_BAAL" 
  after insert on "BIOMART"."BIO_ANALYSIS_ATTRIBUTE"
  for each row
declare
  -- local variables here
begin
  if inserting then       
    -- create a new record in the lineage table for each ancestor of this term (including self)
    insert into BIO_ANALYSIS_ATTRIBUTE_LINEAGE 
    (BIO_ANALYSIS_ATTRIBUTE_ID, ANCESTOR_TERM_ID, ANCESTOR_SEARCH_KEYWORD_ID)
    SELECT :NEW.BIO_ANALYSIS_ATTRIBUTE_ID, skl.ancestor_id, skl.search_keyword_id 
    FROM searchapp.solr_keywords_lineage skl
    WHERE skl.term_id = :NEW.TERM_ID;
  end if;   
  
end TRG_BIO_ANALYSIS_ATT_BAAL;

ALTER TRIGGER "BIOMART"."TRG_BIO_ANALYSIS_ATT_BAAL" DISABLE;



--------------------------------------------------------
--  DDL for Table BIO_ANALYSIS_ATTRIBUTE_LINEAGE
--------------------------------------------------------

  CREATE TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE" 
   (  "BIO_ANALYSIS_ATT_LINEAGE_ID" NUMBER, 
  "BIO_ANALYSIS_ATTRIBUTE_ID" NUMBER, 
  "ANCESTOR_TERM_ID" NUMBER, 
  "ANCESTOR_SEARCH_KEYWORD_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIOMART" ;
--------------------------------------------------------
--  DDL for Index PK_BAAL_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BIOMART"."PK_BAAL_ID" ON "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE" ("BIO_ANALYSIS_ATT_LINEAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIOMART" ;
--------------------------------------------------------
--  Constraints for Table BIO_ANALYSIS_ATTRIBUTE_LINEAGE
--------------------------------------------------------

  ALTER TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE" ADD CONSTRAINT "PK_BAAL_ID" PRIMARY KEY ("BIO_ANALYSIS_ATT_LINEAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BIOMART"  ENABLE;
 
  ALTER TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE" MODIFY ("BIO_ANALYSIS_ATT_LINEAGE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE" MODIFY ("BIO_ANALYSIS_ATTRIBUTE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE" MODIFY ("ANCESTOR_TERM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE" MODIFY ("ANCESTOR_SEARCH_KEYWORD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BIO_ANALYSIS_ATTRIBUTE_LINEAGE
--------------------------------------------------------

  ALTER TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE" ADD CONSTRAINT "FK_BAAL_BAA" FOREIGN KEY ("BIO_ANALYSIS_ATTRIBUTE_ID")
    REFERENCES "BIOMART"."BIO_ANALYSIS_ATTRIBUTE" ("BIO_ANALYSIS_ATTRIBUTE_ID") ENABLE;
 
  ALTER TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE" ADD CONSTRAINT "FK_BAAL_SEARCH_KEYWORD" FOREIGN KEY ("ANCESTOR_SEARCH_KEYWORD_ID")
    REFERENCES "SEARCHAPP"."SEARCH_KEYWORD" ("SEARCH_KEYWORD_ID") ENABLE;
 
  ALTER TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE" ADD CONSTRAINT "FK_BAAL_SEARCH_TAXONOMY" FOREIGN KEY ("ANCESTOR_TERM_ID")
    REFERENCES "SEARCHAPP"."SEARCH_TAXONOMY" ("TERM_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BIO_ANALYSIS_ATT_LINEAGE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BIOMART"."TRG_BIO_ANALYSIS_ATT_LINEAGE" 
  before insert on "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE"
  for each row
declare
  -- local variables here
begin
  if inserting then       
    if :NEW.BIO_ANALYSIS_ATT_LINEAGE_ID is null then
      select SEQ_BIO_ANALYSIS_ATT_LIN_ID.nextval into :NEW.BIO_ANALYSIS_ATT_LINEAGE_ID from dual;
    end if;
  end if;   
end TRG_BIO_ANALYSIS_ATT_LINEAGE;

/
ALTER TRIGGER "BIOMART"."TRG_BIO_ANALYSIS_ATT_LINEAGE" ENABLE;

--------------------------------------------------------
--  DDL for Table SEARCH_TAXONOMY
--------------------------------------------------------

  CREATE TABLE "SEARCHAPP"."SEARCH_TAXONOMY" 
   (           "TERM_ID" NUMBER(22,0), 
                "TERM_NAME" VARCHAR2(900 BYTE), 
                "SOURCE_CD" VARCHAR2(900 BYTE), 
                "IMPORT_DATE" TIMESTAMP (1) DEFAULT Sysdate, 
                "SEARCH_KEYWORD_ID" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT);
--------------------------------------------------------
--  DDL for Index SEARCH_TAXONOMY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEARCHAPP"."SEARCH_TAXONOMY_PK" ON "SEARCHAPP"."SEARCH_TAXONOMY" ("TERM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT);
--------------------------------------------------------
--  Constraints for Table SEARCH_TAXONOMY
--------------------------------------------------------

  ALTER TABLE "SEARCHAPP"."SEARCH_TAXONOMY" ADD CONSTRAINT "SEARCH_TAXONOMY_PK" PRIMARY KEY ("TERM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) ENABLE;

  ALTER TABLE "SEARCHAPP"."SEARCH_TAXONOMY" MODIFY ("TERM_ID" NOT NULL ENABLE);

  ALTER TABLE "SEARCHAPP"."SEARCH_TAXONOMY" MODIFY ("TERM_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SEARCH_TAXONOMY
--------------------------------------------------------

  ALTER TABLE "SEARCHAPP"."SEARCH_TAXONOMY" ADD CONSTRAINT "FK_SEARCH_TAX_SEARCH_KEYWORD" FOREIGN KEY ("SEARCH_KEYWORD_ID")
                  REFERENCES "SEARCHAPP"."SEARCH_KEYWORD" ("SEARCH_KEYWORD_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger TGR_SEARCH_TAXONOMY_TERM_ID
--------------------------------------------------------

-- BEGIN SEQUENCE SEQ_SEARCH_TAXONOMY_TERM_ID
CREATE SEQUENCE SEARCHAPP.SEQ_SEARCH_TAXONOMY_TERM_ID
      INCREMENT BY 2000
      NOMINVALUE
      NOMAXVALUE
      CACHE 20
      NOCYCLE
      NOORDER;
-- END SEQUENCE SEQ_SEARCH_TAXONOMY_TERM_ID

  CREATE OR REPLACE TRIGGER "SEARCHAPP"."TGR_SEARCH_TAXONOMY_TERM_ID" 
  before insert on "SEARCHAPP"."SEARCH_TAXONOMY" for each row
begin 
    If Inserting 
      Then If :New.Term_Id Is Null 
        Then Select Seq_Search_Taxonomy_Term_Id.Nextval Into :New.Term_Id From Dual; 
      End If; 
    end if;
end;


ALTER TRIGGER "SEARCHAPP"."TGR_SEARCH_TAXONOMY_TERM_ID" ENABLE;




--------------------------------------------------------
--  DDL for Table SEARCH_TAXONOMY_RELS
--------------------------------------------------------

  CREATE TABLE "SEARCHAPP"."SEARCH_TAXONOMY_RELS" 
   (           "SEARCH_TAXONOMY_RELS_ID" NUMBER(22,0), 
                "CHILD_ID" NUMBER(22,0), 
                "PARENT_ID" NUMBER(22,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT);
--------------------------------------------------------
--  DDL for Index SYS_C0056419
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEARCHAPP"."SYS_C0056419" ON "SEARCHAPP"."SEARCH_TAXONOMY_RELS" ("SEARCH_TAXONOMY_RELS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT);
--------------------------------------------------------
--  DDL for Index U_CHILD_ID_PARENT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEARCHAPP"."U_CHILD_ID_PARENT_ID" ON "SEARCHAPP"."SEARCH_TAXONOMY_RELS" ("CHILD_ID", "PARENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT);
--------------------------------------------------------
--  Constraints for Table SEARCH_TAXONOMY_RELS
--------------------------------------------------------

  ALTER TABLE "SEARCHAPP"."SEARCH_TAXONOMY_RELS" MODIFY ("CHILD_ID" NOT NULL ENABLE);

  ALTER TABLE "SEARCHAPP"."SEARCH_TAXONOMY_RELS" ADD PRIMARY KEY ("SEARCH_TAXONOMY_RELS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT);

  ALTER TABLE "SEARCHAPP"."SEARCH_TAXONOMY_RELS" ADD CONSTRAINT "U_CHILD_ID_PARENT_ID" UNIQUE ("CHILD_ID", "PARENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT);
--------------------------------------------------------
--  Ref Constraints for Table SEARCH_TAXONOMY_RELS
--------------------------------------------------------

  ALTER TABLE "SEARCHAPP"."SEARCH_TAXONOMY_RELS" ADD CONSTRAINT "FK_SEARCH_TAX_RELS_CHILD" FOREIGN KEY ("CHILD_ID")
                  REFERENCES "SEARCHAPP"."SEARCH_TAXONOMY" ("TERM_ID") ENABLE;

  ALTER TABLE "SEARCHAPP"."SEARCH_TAXONOMY_RELS" ADD CONSTRAINT "FK_SEARCH_TAX_RELS_PARENT" FOREIGN KEY ("PARENT_ID")
                  REFERENCES "SEARCHAPP"."SEARCH_TAXONOMY" ("TERM_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger TGR_SEARCH_TAXONOMY_RELS_ID
--------------------------------------------------------

-- BEGIN SEQUENCE SEQ_SEARCH_TAXONOMY_RELS_ID
CREATE SEQUENCE SEARCHAPP.SEQ_SEARCH_TAXONOMY_RELS_ID
      INCREMENT BY 1
      NOMINVALUE
      NOMAXVALUE
      CACHE 20
      NOCYCLE
      NOORDER;
-- END SEQUENCE SEQ_SEARCH_TAXONOMY_RELS_ID

  CREATE OR REPLACE TRIGGER "SEARCHAPP"."TGR_SEARCH_TAXONOMY_RELS_ID" 
  before insert on searchapp.Search_Taxonomy_rels for each row
begin 
    If Inserting 
      Then If :New.search_taxonomy_rels_Id Is Null 
        Then Select Seq_Search_Taxonomy_rels_Id.Nextval Into :New.search_taxonomy_rels_Id From Dual; 
      End If; 
    end if;
end;

ALTER TRIGGER "SEARCHAPP"."TGR_SEARCH_TAXONOMY_RELS_ID" ENABLE;

CREATE SYNONYM SEARCH_TAXONOMY_RELS FOR SEARCHAPP.SEARCH_TAXONOMY_RELS;
CREATE SYNONYM SEARCH_TAXONOMY FOR SEARCHAPP.SEARCH_TAXONOMY;
CREATE SYNONYM BIO_ANALYSIS_ATTRIBUTE FOR BIOMART.BIO_ANALYSIS_ATTRIBUTE;
CREATE SYNONYM BIO_ANALYSIS_ATTRIBUTE_LINEAGE FOR BIOMART.BIO_ANALYSIS_ATTRIBUTE_LINEAGE;