--DELETE FROM SEARCH_TAXONOMY

--Populate the SEARCH_TAXONOMY tree with the categories we want to see.
INSERT INTO SEARCH_TAXONOMY (TERM_NAME) VALUES ('Categories');
INSERT INTO SEARCH_TAXONOMY (TERM_NAME) VALUES ('Analyses');
INSERT INTO SEARCH_TAXONOMY (TERM_NAME) VALUES ('Study');
INSERT INTO SEARCH_TAXONOMY (TERM_NAME) VALUES ('Region of Interest');
INSERT INTO SEARCH_TAXONOMY (TERM_NAME) VALUES ('Data Type');

--Add a record which makes 'Categories' the top level node.
INSERT INTO SEARCH_TAXONOMY_RELS (CHILD_ID) VALUES (2001);
INSERT INTO SEARCH_TAXONOMY_RELS (CHILD_ID,PARENT_ID) VALUES (4001,2001);

INSERT INTO SEARCH_TAXONOMY_RELS (CHILD_ID,PARENT_ID) SELECT (SELECT TERM_ID FROM SEARCH_TAXONOMY WHERE TERM_NAME = 'Study'),(SELECT TERM_ID FROM SEARCH_TAXONOMY WHERE TERM_NAME = 'Categories') FROM DUAL;
INSERT INTO SEARCH_TAXONOMY_RELS (CHILD_ID,PARENT_ID) SELECT (SELECT TERM_ID FROM SEARCH_TAXONOMY WHERE TERM_NAME = 'Region of Interest'),(SELECT TERM_ID FROM SEARCH_TAXONOMY WHERE TERM_NAME = 'Categories') FROM DUAL;
INSERT INTO SEARCH_TAXONOMY_RELS (CHILD_ID,PARENT_ID) SELECT (SELECT TERM_ID FROM SEARCH_TAXONOMY WHERE TERM_NAME = 'Data Type'),(SELECT TERM_ID FROM SEARCH_TAXONOMY WHERE TERM_NAME = 'Categories') FROM DUAL;

--Add a record to SEARCH_KEYWORD for the GWAS data type.
INSERT INTO SEARCH_KEYWORD (KEYWORD,UNIQUE_ID,DATA_CATEGORY,DISPLAY_DATA_CATEGORY) VALUES ('GWAS','FACETED:DAT:GWAS','DATA_TYPE','Data Type');

--Add a record to SEARCH_TAXONOMY for the GWAS data type.
INSERT INTO SEARCH_TAXONOMY (TERM_NAME,SEARCH_KEYWORD_ID) SELECT 'GWAS',(SELECT SEARCH_KEYWORD_ID FROM SEARCH_KEYWORD WHERE KEYWORD = 'GWAS') FROM DUAL;

--ADD A RECORD TO THE BIO_ANALYSIS_ATTRIBUTE TABLE THAT ASSOCIATES THE GWAS DATA_TYPE WITH THIS ANALYSIS.
INSERT INTO BIOMART.BIO_ANALYSIS_ATTRIBUTE (STUDY_ID,BIO_ASSAY_ANALYSIS_ID,TERM_ID,SOURCE_CD) SELECT '169381',1147409,(SELECT TERM_ID FROM SEARCH_TAXONOMY WHERE TERM_NAME = 'GWAS'),'DATA_TYPE:GWAS' FROM DUAL;

--ADD A RECORD TO THE BIO_EXPERIMENT TABLE.

DELETE FROM BIOMART.BIO_ANALYSIS_ATTRIBUTE

SELECT * FROM BIO_EXPERIMENT WHERE ROWNUM <= 10;




SELECT search_keyword_id SEARCH_KEYWORD_ID FROM bio_analysis_attribute baa, search_keyword sk
							   WHERE baal.bio_analysis_attribute_id=baa.bio_analysis_attribute_id AND baal.ancestor_search_keyword_id=sk.search_keyword_id
													   AND baa.bio_assay_analysis_id='1147409'
													   AND sk.data_category='ANALYSES'

SELECT * FROM SEARCH_TAXONOMY;
SELECT * FROM SEARCH_TAXONOMY_RELS;

--1147409 BIO_ASSAY_ANALYSIS_ID
SELECT * FROM BIOMART.BIO_ASSAY_ANALYSIS_GWAS WHERE ROWNUM <= 10;
SELECT * FROM BIO_ASSAY_ANALYSIS WHERE BIO_ASSAY_ANALYSIS_ID = 1147409;

SELECT * FROM BIO_DATA_DISEASE WHERE BIO_DATA_ID = 1147409;