-- indexes for faster uploads

CREATE INDEX I2B2DEMODATA.PD_SOURCESYSTEMCD_IDX ON I2B2DEMODATA.PATIENT_DIMENSION (SOURCESYSTEM_CD);
create index TM_WZ.idx_wrk_cd on TM_WZ.WRK_CLINICAL_DATA("DATA_TYPE","DATA_VALUE","VISIT_NAME","DATA_LABEL","CATEGORY_CD","USUBJID");
create index TM_WZ.IDX_WT_TRIALNODES on TM_WZ.WT_TRIAL_NODES("LEAF_NODE");


