CREATE SCHEMA IF NOT EXISTS I2B2METADATA;
CREATE SCHEMA IF NOT EXISTS I2B2DEMODATA;
CREATE SCHEMA IF NOT EXISTS DEAPP;
CREATE SCHEMA IF NOT EXISTS BIOMART;
CREATE SCHEMA IF NOT EXISTS SEARCHAPP;
SET SCHEMA_SEARCH_PATH PUBLIC,I2B2METADATA,I2B2DEMODATA,BIOMART;
