


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.13 at 10:06:04 AM EST 
//


package com.recomdata.util.ariadne;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}styles"/>
 *         &lt;element ref="{}scene"/>
 *       &lt;/sequence>
 *       &lt;attribute name="owner" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "styles",
        "scene"
})
@XmlRootElement(name = "layout")
public class Layout {

    @XmlElement(required = true)
    protected Styles styles;
    @XmlElement(required = true)
    protected Scene scene;
    @XmlAttribute
    protected String owner;

    /**
     * Gets the value of the styles property.
     *
     * @return possible object is
     * {@link Styles }
     */
    public Styles getStyles() {
        return styles;
    }

    /**
     * Sets the value of the styles property.
     *
     * @param value allowed object is
     *              {@link Styles }
     */
    public void setStyles(Styles value) {
        this.styles = value;
    }

    /**
     * Gets the value of the scene property.
     *
     * @return possible object is
     * {@link Scene }
     */
    public Scene getScene() {
        return scene;
    }

    /**
     * Sets the value of the scene property.
     *
     * @param value allowed object is
     *              {@link Scene }
     */
    public void setScene(Scene value) {
        this.scene = value;
    }

    /**
     * Gets the value of the owner property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOwner(String value) {
        this.owner = value;
    }

}
